### ISSUE TITLE
Error on use ProtocolLib 5.0 (CombatLogX)

### ISSUE THREAD

**Issue by AkariDream** [SirBlobman/SirBlobmanAPI#33]
**Describe the bug**
SirBlobmanCore does not yet support ProtocolLib 5.0 causing a Player to join the game when CombatLogX issues an error _//maybe_
**imm not sure if this is a question of CombatLogX or SirBlobManCore. anyway, I just want to fix it. :(**

**To Reproduce**
- Drop the latest build ProtocolLib5.0 And CombatLogX,SirBlobmanAPI in the plugins
- Join server. he happened

**Expected behavior**
:\

**Minecraft Version**
 - 1.18.2 Paper#379  

**SirBlobmanCore Version:**
 - 2.3.6 (spigot latest)  //Clx 10.4.2.4 (sipgot latest)

**Additional context**
_Unhandled exception number 2048 occurred in onPacketSending(PacketEvent)_

java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/server/TemporaryPlayer
        at com.SirBlobman.combatlogx.api.olivolja3.force.field.ForceFieldAdapter.onPacketSending(ForceFieldAdapter.java:80) ~[CombatLogX.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib5.0(#569).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib5.0(#569).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[ProtocolLib5.0(#569).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib5.0(#569).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:95) ~[ProtocolLib5.0(#569).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:525) ~[ProtocolLib5.0(#569).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib5.0(#569).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib5.0(#569).jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2040) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2026) ~[?:?]
        at net.minecraft.server.level.ChunkHolder.broadcast(ChunkHolder.java:423) ~[?:?]
        at net.minecraft.server.level.ChunkHolder.broadcastChanges(ChunkHolder.java:363) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1056) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:907) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:629) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1593) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.injector.server.TemporaryPlayer
        ... 24 more

Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutBlockChange@4a35b729[
    a=BlockPosition{x=-3740, y=76, z=5372}
    b=Block{minecraft:water}[level=7]
  ]

**Comment by SirBlobman** [comment]
If you're using 1.18.2, you should be using CombatLogX Beta. 

https://jenkins.sirblobman.xyz/job/SirBlobman/job/SirBlobmanAPI/
https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/
